OWManifoldLearning: Clean up UX
biolab/orange3 pull request #5257
Opened 2021-02-11 18:28 UTC by janezd

### Issue

I refreshed Manifold Learning as discussed on Tuesday on @irgolic's *Widgets showing show*.

Closes #5248.

### Description of changes

- Use `QFormLayout` so that controls are properly aligned
- Replace spins with line edits
- Put parameters in the same box as the combo for selecting the method. These are method's parameters, and they even change when the method is changed, so I think they must be in the same box.

<img width="687" alt="Screenshot 2021-02-11 at 19 24 59" src="https://user-images.githubusercontent.com/2387315/107681231-1736cf80-6c9f-11eb-91bf-7cbd5ff5f051.png">

### Considerations

- I'm having second thoughts about removing the (now unnecessary) `_create_spin_parameter`. Do we keep it, just for the case we need it in the future? The method for check boxes is also still threre.
- Number of components is still a spin, because it probably makes sense. Keep it like this or turn it into line edit, too?
- I haven't tried whether the widget still works. :) It seems to pass the tests, though.

##### Includes
- [X] Code changes

2021-02-12 10:19 UTC, ajdapretnar commented
Locally Linear Embedding looks a bit off, but the rest are ok.

2021-02-12 12:07 UTC, VesnaT requested changes
The `QIntValidator` does not suffice and I'm getting various error typing into the line edits.

2021-02-12 16:54 UTC, janezd commented on Orange/widgets/unsupervised/owmanifoldlearning.py
> +        self.perplexity_spin = self._create_line_edit_parameter(
I wonder who introduced those variables in the first place. Who's to `blame`? :)

You're right, though. I removed them in the second commit.

2021-02-12 16:57 UTC, janezd commented
I scaled this back. `QIntValidator` sucks, so I went back to spins, but in form layout and fixed width.

Except for removing unnecessary variables, this is now only about layout.

2021-02-15 08:44 UTC, VesnaT approved these changes

2021-02-15 08:45 UTC, merged