sqltable compute nan frequency
biolab/orange3 pull request #6353
Opened 2023-02-27 11:58 UTC by noahnovsak

##### Issue
`__get_nan_frequency' uses X and Y arrays, so SqlTables need an alternative implementation.

2023-02-27 12:29 UTC, markotoplak commented
@lanzagar or @PrimozGodec: can one of you please check this PR? Thanks!

2023-03-03 10:58 UTC, PrimozGodec requested changes

2023-03-03 10:58 UTC, PrimozGodec commented on Orange/tests/sql/test_sql_table.py
> +    @dbt.run_on(["postgres"])
It should be also tested on mssql

```suggestion
    @dbt.run_on(["postgres", "mssql"])
```

2023-03-03 10:58 UTC, PrimozGodec commented on Orange/data/sql/table.py
> +                                    filters=[f"{col_field} IS NULL OR {col_field} = 'NaN'"])
Checking NULL is sufficient. Checking `"nan"` even fail on MSSQL when column is float.
```suggestion
        query = self._sql_query(["COUNT(*)"], filters=[f"{col_field} IS NULL"])
```

2023-03-03 10:58 UTC, PrimozGodec commented on Orange/data/sql/table.py
> +                                    filters=[f"{col_field} IS NULL OR {col_field} = 'NaN'"])
Anyway, can we make it in one query to speed the process up? For example with this: https://stackoverflow.com/a/16528738/3551700

2023-03-03 11:01 UTC, PrimozGodec commented
Additionally (not connected with your changes but required to insert NULL values in database correctly) `Orange.test.base` lines 280-285 should be changed to:
```
        insert_values = ", ".join(
            "({})".format(
                ", ".join(
                    "NULL" if pd.isna(v) else "'{}'".format(v)
                    for v, t in zip(row, sql_column_types)
                )
            )
            for row in data
        )
```
I replaced v is None with pd.isna(v) to correctly handle None and nan values.

2023-03-10 08:37 UTC, merged

2023-03-10 08:37 UTC, PrimozGodec commented
@noahnovsak thank you for patience.